myblog/auth/urls.py
from django.urls import re_path
from auth import views

app_name = 'auth'

urlpatterns = [
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^user/(?P<pk>\d+)/profile/$', views.profile, name='profile'),
    re_path(r'^user/(?P<pk>\d+)/profile/update/$', views.profile_update, name='profile_update'),
    re_path(r'^user/(?P<pk>\d+)/pwd_change/$', views.pwd_change, name='pwd_change'),
    re_path(r"^logout/$", views.logout, name='logout')
]

myblog/blog/urls.py
from . import views
from django.urls import path, include

app_name = 'blog'
urlpatterns = [
    # localhost:8000/blog/
    path('', views.index, name='index'),
    path('work/', views.work, name = 'work'),
    path('person/', views.person, name = 'person'),
    path('article-list/', views.BlogListView.as_view(), name = 'article-list'),
    path('contact/', views.contact, name = 'contact'),
    path('<int:article_id>/', views.detail, name = 'detail'),
    path('post_comment/<int:article_id>', views.post_comment, name = 'post_comment'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', views.index, name='index'),
    path('blog/', include('blog.urls')),
    path('account/', include('users.urls')),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/blog/models.py
import datetime
from django.db import models
from django.utils import timezone
from mdeditor.fields import MDTextField
from imagekit.processors import ResizeToFill
from imagekit.models import ImageSpecField
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length = 255)
    body = MDTextField(null = True)
    desc = models.TextField(default = '')
    cover = models.ImageField(upload_to = 'images/', default = 'default.jpg')
    views = models.IntegerField(default = 0)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    processed_photo = ImageSpecField(
            source="cover",
            processors=[ResizeToFill(750, 375)], # 处理后的图像大小
            format='JPEG',  # 处理后的图片格式
            options={'quality': 98} # 处理后的图片质量
        )
    
    processed_photo_type2 = ImageSpecField(
            source="cover",
            processors=[ResizeToFill(60, 60)], # 处理后的图像大小
            format='JPEG',  # 处理后的图片格式
            options={'quality': 98} # 处理后的图片质量
        )

    def __str__(self):
        return self.title

    class Meta:
    	ordering = ['-created_at']

class Comment(models.Model):
    comment = models.TextField()
    article = models.ForeignKey(Article, on_delete = models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    pub_date = models.DateTimeField(auto_now_add = True)

myblog/blog/views.py
from django.shortcuts import get_object_or_404, render
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.list import ListView
from .models import Article
from .models import Comment
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime
import markdown
import json
from django.urls import reverse
from django.core.cache import cache

# Create your views here.

def index(request):
    return render(request, 'blog/index.html')

def work(request):
    return render(request, 'blog/work.html')

def person(request):
    return render(request, 'blog/person.html')

def contact(request):
    return render(request, 'blog/contact.html')

def top(request):
    return render(request, 'blog/top.html')

def header(request):
    return render(request, 'blog/header.html')

def foot(request):
    return render(request, 'blog/foot.html')

def hot_articles():
    md_key = f"most_view_md_{datetime.now().hour}"
    # Adding '-' to the column name indicates that the results are in descending order.
    if cache.has_key(md_key):
        articles = cache.get(md_key)
    else:
        # Hot articles are updated every an hours
        articles = Article.objects.order_by('-views')[:3]
        cache.set(md_key, articles, 60 * 60)
    return articles

class BlogListView(ListView):
    model = Article
    paginate_by = 3

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BlogListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['hot_articles'] = hot_articles()
        return context

def detail(request, article_id):
    article = get_object_or_404(Article, pk = article_id)
    article.views = F('views') + 1
    article.save()
    article = get_object_or_404(Article, pk = article_id)
    # md_key = f"{article.id}_md_key_{datetime.timestamp(article.created_at)}"
    # if cache.has_key(md_key):
    #     article.body = cache.get(md_key)
    # else:
    #     article.body = markdown.markdown(
    #             article.body,
    #             extensions=[
    #                 'markdown.extensions.extra',
    #                 'markdown.extensions.codehilite',
    #                 'markdown.extensions.toc',
    #             ],
    #             safe_mode = True,
    #             enable_attributes = False
    #         )
    #     cache.set(md_key, article.body, 60*60*24)
    article.body = markdown.markdown(
            article.body,
            extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.toc',
            ],
            safe_mode = True,
            enable_attributes = False
        )
    comments = article.comments.all()
    return render(request, 'blog/article_detail.html', {'article' : article, 'comments' : comments, 'hot_articles': hot_articles()})

def post_comment(request, article_id):
    comment = request.POST.get('comment')
    if comment:
        Comment.objects.create(comment=comment, article_id=article_id)
    else:
        print("no comment")
    return HttpResponseRedirect(reverse('blog:detail', args=(article_id, )))

myblog/blog/templates/blog/article_detail.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html class="no-js" lang="zxx">
  {% include "blog/top.html" %}

  <body class="full-wrapper">
    {% include "blog/header.html" %}
    <!-- header end -->
    <main>
      <!--? Blog Area Start -->
      <section class="blog_area single-post-area section-padding">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 posts-list">
              <div class="single-post">
                <div class="feature-img">
                  <img class="img-fluid" src="{{ article.processed_photo.url }}" alt="">
                </div>
                <div class="blog_details">
                  <h2 style="color: #2d2d2d">
                    {{ article.title }}
                  </h2>
                  <ul class="blog-info-link mt-3 mb-4">
                    <li>
                      <a href="#"
                        ><i class="fa fa-user"></i> {{ article.views }} views</a
                      >
                    </li>
                    <li>
                      <a href="#"><i class="fa fa-comments"></i>{{ comments.count }} comments</a>
                    </li>
                  </ul>
                  <p> {{ article.body | safe }} </p>
                </div>
              </div>
              <div class="comments-area">
                <h4>{{ comments.count }} comments</h4>
                {% for c in comments %}
                  <div class="comment-list">
                      <div class="single-comment justify-content-between d-flex">
                        <div class="user justify-content-between d-flex">
                          <div class="thumb">
                            <img src="{% static "blog/img/blog/comment.png" %}" alt="">
                          </div>
                          <div class="desc">
                            <p class="comment">
                              {{ c.comment }}
                            </p>
                            <div class="d-flex justify-content-between">
                              <div class="d-flex align-items-center">
                                <h5>
                                  <a href="#">游客</a>
                                </h5>
                                <p class="date">{{ c.pub_date|naturaltime }}</p>
                              </div>
                              <div class="reply-btn">
                                <a href="#" class="btn-reply text-uppercase"
                                  >reply</a
                                >
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>            
                  </div>
                {% empty %}
                  <li>No Comment yet.</li>
                {% endfor %}
              </div>
              <div class="comment-form">
                <h4>Leave a Reply</h4>
                <form
                  class="form-contact comment_form"
                  id="commentForm"
                  action="{% url 'blog:post_comment' article.id %}"
                  method='post'
                >
                {% csrf_token %}
                  <div class="row">
                    <div class="col-12">
                      <div class="form-group">
                        <textarea
                          class="form-control w-100"
                          name="comment"
                          id="comment"
                          cols="30"
                          rows="9"
                          placeholder="Write Comment"
                        ></textarea>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <button
                      type="submit"
                      class="button button-contactForm btn_1 boxed-btn"
                    >
                      Post Comment
                    </button>
                  </div>
                </form>
              </div>
            </div>
          {% include "blog/right_sidebar.html" %}
          </div>
        </div>
      </section>
      <!-- Blog Area End -->
    </main>
    {% include "blog/foot.html" %}
  </body>
</html>

myblog/blog/templates/blog/article_list.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
{% include "blog/top.html" %}

<body class="full-wrapper">
    <!-- ? Preloader Start -->
    {% include "blog/header.html" %}
    <main>
        <!-- Hero Area End-->
        <!--? Blog Area Start-->
        <section class="blog_area section-padding">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mb-5 mb-lg-0">
                        <div class="blog_left_sidebar">
                            {% for article in object_list %}
                            <article class="blog_item">
                                <div class="blog_item_img">
                                    <img class="card-img rounded-0" src="{{ article.processed_photo.url }}" alt="">
                                    <a href="#" class="blog_item_date">
                                        <h3>{{ article.created_at|date }}</h3>
                                    </a>
                                </div>
                                <div class="blog_details">
                                    <a class="d-inline-block" href="{% url 'blog:detail' article.id %}">
                                        <h2 class="blog-head" style="color: #2d2d2d;">{{ article.title }}</h2>
                                    </a>
                                    <p>{{ article.desc }}</p>
                                    <ul class="blog-info-link">
                                        <li><i class="fa fa-user"></i> {{ article.views }} views</li>
                                        <li><i class="fa fa-comments"></i> {{ article.comment_set.count }} Comments</li>
                                    </ul>
                                </div>
                            </article>
                            {% empty %}
                                <li>No blog yet.</li>
                            {% endfor %}
                            <nav class="blog-pagination justify-content-center d-flex">
                                <ul class="pagination">
                                    <li class="page-item">
                                        {% if page_obj.has_previous %}
                                        <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
                                            {% comment %} <i class="ti-angle-left"><a href="?page=1">&laquo; first</a></i> {% endcomment %}
                                            <i class="ti-angle-left"></i>
                                        </a>
                                        {% endif %}
                                    </li>

                                    <li class="page-item">
                                        <a href="#" class="page-link">{{ page_obj.number }}</a>
                                    </li>

                                    <li class="page-item">
                                        {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                                            <i class="ti-angle-right"></i>
                                            {% comment %} <i class="ti-angle-right"><a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></i> {% endcomment %}
                                        </a>
                                        {% endif %}
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    {% include "blog/right_sidebar.html" %}
                </div>
            </div>
        </section>
        <!-- Blog Area End -->
    </main>
    {% include "blog/foot.html" %}
</body>

</html>

myblog/blog/templates/blog/foot.html
{% load static %}
<!-- footer-bottom area -->
<footer>
    <div class="footer-bottom-area">
        <div class="container">
            <div class="footer-border">
                <div class="row d-flex align-items-center">
                    <div class="col-xl-12 ">
                        <div class="footer-copy-right text-center">
                            <p>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved | This
                                template is made with by
                                <i class="fa fa-heart" aria-hidden="true"></i><a href="https://github.com/zhongyuhang"
                                    target="_blank">YH</a>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End-->
</footer>
<!--? Search model Begin -->
<div class="search-model-box">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-btn">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Searching key.....">
        </form>
    </div>
</div>
<!-- Search model end -->
<!-- Scroll Up -->
<div id="back-top">
    <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
</div>
<!-- JS here -->
<!-- Jquery, Popper, Bootstrap -->
<script src="{% static "blog/js/vendor/modernizr-3.5.0.min.js" %}"></script>
<script src="{% static "blog/js/vendor/jquery-1.12.4.min.js" %}"></script>
<script src="{% static "blog/js/popper.min.js" %}"></script>
<script src="{% static "blog/js/bootstrap.min.js" %}"></script>

<!-- Slick-slider , Owl-Carousel ,slick-nav -->
<script src="{% static "blog/js/owl.carousel.min.js" %}"></script>
<script src="{% static "blog/js/slick.min.js" %}"></script>
<script src="{% static "blog/js/jquery.slicknav.min.js" %}"></script>

<!-- One Page, Animated-HeadLin, Date Picker -->
<script src="{% static "blog/js/wow.min.js" %}"></script>
<script src="{% static "blog/js/animated.headline.js" %}"></script>
<script src="{% static "blog/js/jquery.magnific-popup.js" %}"></script>
<script src="{% static "blog/js/gijgo.min.js" %}"></script>

<!-- Nice-select, sticky,Progress -->
<script src="{% static "blog/js/jquery.nice-select.min.js" %}"></script>
<script src="{% static "blog/js/jquery.sticky.js" %}"></script>
<script src="{% static "blog/js/jquery.barfiller.js" %}"></script>

<!-- counter , waypoint,Hover Direction -->
<script src="{% static "blog/js/jquery.counterup.min.js" %}"></script>
<script src="{% static "blog/js/waypoints.min.js" %}"></script>
<script src="{% static "blog/js/jquery.countdown.min.js" %}"></script>
<script src="{% static "blog/js/hover-direction-snake.min.js" %}"></script>

<!-- contact js -->
<script src="{% static "blog/js/contact.js" %}"></script>
<script src="{% static "blog/js/jquery.form.js" %}"></script>
<script src="{% static "blog/js/jquery.validate.min.js" %}"></script>
<script src="{% static "blog/js/mail-script.js" %}"></script>
<script src="{% static "blog/js/jquery.ajaxchimp.min.js" %}"></script>

<!-- Jquery Plugins, main Jquery -->
<script src="{% static "blog/js/plugins.js" %}"></script>
<script src="{% static "blog/js/main.js" %}"></script>

myblog/blog/templates/blog/header.html
{% load static %}
<div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-inner position-relative">
            <div class="preloader-circle"></div>
            <div class="preloader-img pere-text">
                <img src="{% static "blog/img/logo/loder.png" %}" alt="">
            </div>
        </div>
    </div>
</div>
<!-- Header Start -->
<div class="header-area ">
    <div class="main-header header-sticky">
        <div class="container-fluid">
            <div class="menu-wrapper d-flex align-items-center justify-content-between">
                <div class="header-left d-flex align-items-center">
                    <!-- Logo -->
                    <div class="logo">
                        <a href="{% url 'blog:index' %}"><img src="{% static "blog/img/logo/logo.png" %}"></a>
                    </div>
                    <!-- Main-menu -->
                    <div class="main-menu  d-none d-lg-block">
                        <nav>
                            <ul id="navigation">
                                <li><a href="{% url 'blog:person' %}">Me</a></li>
                                <li><a href="{% url 'blog:article-list' %}">Blog</a></li>
                                {% comment %} <li><a href="{% url 'blog:contact' %}">Contact</a></li> {% endcomment %}
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="header-right1 d-flex align-items-center">
                    <div class="header-social d-none d-md-block">
                    {% if user.is_authenticated %}
                        <a href="/account/profile/">{{ user.username | upper | slice:"1" }}</a>
                    {% else %}
                        <a href="/account/login/">登陆</a>
                    {% endif %}
                    <a href="/account/logout/">注销</a>
                    </div>
                </div>
                <!-- Mobile Menu -->
                <div class="col-12">
                    <div class="mobile_menu d-block d-lg-none"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Header End -->
</header>

myblog/blog/templates/blog/index.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
{% include "blog/top.html" %}

<body class="full-wrapper">
    <!-- ? Preloader Start -->
    {% include "blog/header.html" %}
    <main>
        <!--? Hero Area Start-->
        <div class="container-fluid">
            <div class="slider-area">
                <!-- Mobile Device Show Menu-->
                <div class="header-right2 d-flex align-items-center">
                    <!-- Social -->
                    <div class="header-social  d-block d-md-none">
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="https://bit.ly/sai4ull"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-pinterest-p"></i></a>
                    </div>
                    <!-- Search Box -->
                    <div class="search d-block d-md-none">
                        <ul class="d-flex align-items-center">
                            <li class="mr-15">
                                <div class="nav-search search-switch">
                                    <i class="ti-search"></i>
                                </div>
                            </li>
                            <li>
                                <div class="card-stor">
                                    <img src="{% static "blog/img/gallery/card.svg" alt="" %}">
                                    <span>0</span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /End mobile  Menu-->

                <div class="slider-active dot-style">
                    <!-- Single -->
                    <div class="single-slider slider-bg1 hero-overly slider-height d-flex align-items-center">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-xl-8 col-lg-9">
                                    <!-- Hero Caption -->
                                    <div class="hero__caption">
                                        <h1>YES<br>IT'S<br>ME</h1>
                                        <a href="{% url 'blog:contact' %}" class="btn">Know Me</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Single -->
                    <div class="single-slider slider-bg2 hero-overly slider-height d-flex align-items-center">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-xl-8 col-lg-9">
                                    <!-- Hero Caption -->
                                    <div class="hero__caption">
                                        <h1>YES<br>IT'S<br>ME</h1>
                                        <a href="{% url 'blog:contact' %}" class="btn">Know Me</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Single -->
                    <div class="single-slider slider-bg3 hero-overly slider-height d-flex align-items-center">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-xl-8 col-lg-9">
                                    <!-- Hero Caption -->
                                    <div class="hero__caption">
                                        <h1>YES<br>IT'S<br>ME</h1>
                                        <a href="{% url 'blog:contact' %}" class="btn">Know Me</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Hero -->
        <!--? Popular Items Start -->
        <div class="popular-items pt-50">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="single-popular-items mb-50 text-center wow fadeInUp" data-wow-duration="1s"
                            data-wow-delay=".1s">
                            <div class="popular-img">
                                <img src="{% static "blog/img/gallery/popular1.png" %}">
                                <div class="img-cap">
                                    <span>我的新眼镜</span>
                                </div>
                                <div class="favorit-items">
                                    {# <a href="shop.html" class="btn">Know Me</a> #}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="single-popular-items mb-50 text-center wow fadeInUp" data-wow-duration="1s"
                            data-wow-delay=".2s">
                            <div class="popular-img">
                                <img src="{% static "blog/img/gallery/popular2.png" %}">
                                <div class="img-cap">
                                    <span>和男朋友吃食堂</span>
                                </div>
                                <div class="favorit-items">
                                    {# <a href="shop.html" class="btn">Know Me</a> #}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="single-popular-items mb-50 text-center wow fadeInUp" data-wow-duration="1s"
                            data-wow-delay=".4s">
                            <div class="popular-img">
                                <img src="{% static "blog/img/gallery/popular3.png" %}">
                                <div class="img-cap">
                                    <span>等着吃宵夜</span>
                                </div>
                                <div class="favorit-items">
                                    {# <a href="shop.html" class="btn">Know Me</a> #}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="single-popular-items mb-50 text-center wow fadeInUp" data-wow-duration="1s"
                            data-wow-delay=".6s">
                            <div class="popular-img">
                                <img src="{% static "blog/img/gallery/popular4.png" %}">
                                <div class="img-cap">
                                    <span>试试新衣服</span>
                                </div>
                                <div class="favorit-items">
                                    {# <a href="shop.html" class="btn">Know Me</a> #}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--? New Arrival End -->
            <!--? collection -->
            <section class="collection section-bg2 section-padding30 section-over1 ml-15 mr-15"
                data-background="{% static "blog/img/gallery/section_bg01.png" %}">
                <div class="container-fluid"></div>
                <div class="row justify-content-center">
                    <div class="col-xl-7 col-lg-9">
                        <div class="single-question text-center">
                            <h2 class="wow fadeInUp" data-wow-duration="2s" data-wow-delay=".1s">我和他的故事</h2>
                            <a href="#" class="btn" class="wow fadeInUp" data-wow-duration="2s"
                                data-wow-delay=".4s">About Us</a>
                        </div>
                    </div>
                </div>
            </section>
    </main>
    {% include "blog/foot.html" %}
</body>

</html>

myblog/blog/templates/blog/top.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Serendipity</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static "blog/img/favicon.ico" %}">

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static "blog/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/slicknav.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/progressbar_barfiller.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/gijgo.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/animate.min.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/animated-headline.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/fontawesome-all.min.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/themify-icons.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/slick.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/nice-select.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/style.css" %}">

</head>